### ISSUE TITLE
Tezos Ledger Nano S KT wallet withdrawal issue

### ISSUE THREAD

**Issue by kevin-highmark** [obsidiansystems/ledger-app-tezos#106]
I've been trying for weeks trying to withdraw from my KT address KT1Fo19AvYnGYAPyq4WBBfRfvt3YGLokoWvn to my tz tz1abT3iLZULMNFVCgm6XWiCLipghxj33cp1 to redelegate.

However, every time I use any of the wallets (TezBox, Magnum, Galleon), I get an error. TezBox says Uh Oh! Operation Failed Hardware device error. I have the latest firmware and app version for XTZ on my Ledger nano. It fails on Magnum (error 0x917e) and Galleon as well. Any help would be appreciated. I'm basically locked out of my balance completely at this point.

The Ledger doesn't show any error or action for me to take before the wallets error out the transaction. It must be a Ledger app issue since this is happening across all the wallets.

**Comment by mikereinhart** [comment]
@kevin-highmark I know we connected through another channel and discussed this issue. Did it get resolved after the Tezbox update?

**Comment by kevin-highmark** [comment]
@mikereinhart hey mike, I used the latest TezBox 6.0.1 Mac app and it still isn't working. I also am using the WebApp as well and still get the same Device Error error.

**Comment by kevin-highmark** [comment]
This was fixed, but required a lot of unplugging and restarting.

**Comment by mikereinhart** [comment]
Thanks for the update!

**Comment by djdevz** [comment]
@mikereinhart I'm having the same issue - did you ever manage to resolve this? If so, how? Thanks

**Comment by djdevz** [comment]
@kevin-highmark what specifically worked for you? I'm having the same issue. Thanks

**Comment by NikolaiTez** [comment]
you need to change node you can do that via Tezbox web wallet not the app. go there
[https://wallet.tezbox.com/](https://tezbox.io)
