### ISSUE TITLE
Broken link in readme

### ISSUE THREAD

**Issue by songproducer** [obsidiansystems/ledger-app-tezos#115]
> Registering the Ledger device with the node
> ...
> Currently there are two other ways to do this:
> If you have the Nix package manager, use the Tezos baking platform.
> Build tezos from the tezos repo with [these instructions]

"these instructions" links to broken link.

**Comment by jmininger** [comment]
@songproducer the link has been fixed in the README.md. This is the updated link: http://tezos.gitlab.io/introduction/howtoget.html#build-from-sources
Thank you
