### ISSUE TITLE
Signing arbitrary byte sequences

### ISSUE THREAD

**Issue by rvem** [obsidiansystems/ledger-app-tezos#125]
It is possible to sign byte sequences that have `0x03` prefixes (using `tezos-client`).
E.g.
```
XPS-15-9560 :: ~ » tezos-client-babylonnet -A jupiter.serokell.io -P 8732 sign bytes 0x031234abcd for ledger_roman
Warning:
  
                 This is NOT the Tezos Mainnet.
  
     The node you are connecting to claims to be running on the
               Tezos Alphanet DEVELOPMENT NETWORK.
          Do NOT use your fundraiser keys on this network.
          Alphanet is a testing network, with free tokens.

Signature: edsigtxEQK1JyUH6VhzWowhHiS38y7vqVk2gZTvabtnT9qSi3EUt37eVfY1iytwWnD5xmLBNszLKD1pg6k9Kedov3b66xy4W2LD

```
However, when the byte sequence has another prefix, e.g. 0x05 (which corresponds to some packed Michelson value), the command fails.
```
XPS-15-9560 :: ~ » tezos-client-babylonnet -A jupiter.serokell.io -P 8732 sign bytes 0x051234abcd for ledger_roman
Warning:
  
                 This is NOT the Tezos Mainnet.
  
     The node you are connecting to claims to be running on the
               Tezos Alphanet DEVELOPMENT NETWORK.
          Do NOT use your fundraiser keys on this network.
          Alphanet is a testing network, with free tokens.

Error:
  Ledger Application level error (sign-with-hash): Parse error
```
Is this behaviour expected?

In one of our projects, we sign multisig operations for [generic multisig contract](https://github.com/murbard/smart-contracts/blob/master/multisig/michelson/generic.tz). The value that has to be signed for this contract is Michelson lambda (which also has `0x05` prefix in packed representation)

**Comment by mikereinhart** [comment]
@rvem Which version of the ledger app are you using?

**Comment by rvem** [comment]
Version 2.2.1 installed from ledger-live app

**Comment by mikereinhart** [comment]
Thanks! The best way to do this is to use the `INS_SIGN_WITH_HASH` APDU and do blake2b hashing in your application. For more information about supported APDUs, I recommend reading https://github.com/obsidiansystems/ledger-app-tezos/blob/master/APDUs.md

Unfortunately there's currently not a way to do what you're attempting through `tezos-client`.

**Comment by rvem** [comment]
Is it possible to do this using https://github.com/LedgerHQ/ledgerjs and https://github.com/RoMarQ/hw-app-xtz?

**Comment by jonored** [comment]
Yes, with hw-app-xtz just call signHash (instead of signOperation) with your hash bytes and you'll hit the right endpoint. You'll need to find a blake2b implementation on your own, though, I don't believe there is one included with hw-app-xtz.

**Comment by rvem** [comment]
So the `signHash` from hw-app-xtz uses 0x05 operation, which is `INS_SIGN_UNSAFE` [here](https://github.com/obsidiansystems/ledgerjs/blob/4a474d92c25d3fbea91c1bbeae1388c6ae4cd2ce/packages/hw-app-xtz/src/Tezos.js#L179). However, @mikereinhart suggested using INS_SIGN_WITH_HASH which is 0x0F according to [doc](https://github.com/obsidiansystems/ledger-app-tezos/blob/master/APDUs.md). It seems, that `INS_SIGN_WITH_HASH` is not presented in hw-app-xtz :(

**Comment by jonored** [comment]
Sorry, just noticed this; the instruction you want is indeed INS_SIGN_UNSAFE, not INS_SIGN_WITH_HASH - INS_SIGN_WITH_HASH just makes the response from the ledger include the blake2b hash of the bytes you signed, while INS_SIGN_UNSAFE allows you to perform the hash yourself (and thus bypass the operation parsing on the ledger).

**Comment by rvem** [comment]
Great, thanks for the clarification, I think that the issue can be closed now.

**Comment by jonored** [comment]
Just to be clear, this _is_ a workaround, not a real solution; the proper solution ultimately is to provide a mechanism to prove to the ledger what the message is, and a reasonable interim is to have the ledger parse 0x05 messages and display some verifiable message for it.
