### ISSUE TITLE
Acces curve bip25519 accounts using ledger live/tezbox or any other online wallet with ledger nano S.

### ISSUE THREAD

**Issue by lucgoldman** [obsidiansystems/ledger-app-tezos#138]
Hello,

I'm pretty new to this. I ran my own node and baker for some time using kiln on unbuntu. 
Now I want to stop de baker and tranfer my tezz from the tezos baker account to my tezos wallet account. 
The baker account uses the curve bip25519 and derivation path 44'/1729'/0'/0'. When i open my ledger nano S with tezbox, galleon, ledger live or any other wallet, they all only open de ed25519 curve. So i can't transfer any of my tezz. 
Is there a way to get acces to the curve bip25519 accounts using the ledger with ledger live/tezbox/galleon? 
Or in order to send my tezz from the bip25519 curve to my tezos wallet ed25519 curve, must I run a tezos client, register the bip25519 accounts and transfer them using de tezos client?

**Comment by mikereinhart** [comment]
Hello! If wallet providers do not support that curve, you will need to use tezos-client to transfer to a curve (ed25519) supported by 3rd party. I recommend reaching out to the wallet provider of your choice with a feature request to support addresses on this curve. 

One thing that may make your life easier - you can run tezos-client using Kiln on Ubuntu. [You can find the docs here!](https://gitlab.com/obsidian.systems/kiln/-/blob/develop/docs/distros/ubuntu.md#running-tezos-client-and-tezos-admin-client-binaries)

**Comment by lucgoldman** [comment]
Thank you Mike. I will look into the instructions, hopefully that will solve my issue.
