### ISSUE TITLE
Feature Request: Quitting the baking application should lock the ledger

### ISSUE THREAD

**Issue by adrianbrink** [obsidiansystems/ledger-app-tezos#14]
I think it would be a good security measure if on hitting the left button to quit the baking application the ledger would lock itself. That way it would ensure that no one can send any unauthorized transaction even if they gain access to a baking ledger.

I am not sure whether the ledger-sdk supports locking the ledger on button presses, but if it does it would be a great addition.

**Comment by ondrapaulicek** [comment]
"they" cannot send any unauthorized transactions from the ledger used for baking, because that ledger should not have wallet app installed. in order to install the app, you need to know the pin.

**Comment by jhartzell42** [comment]
Yeah, just do not install other apps on baking ledger :-)

**Comment by adrianbrink** [comment]
That's the other solution to this problem. However, it would still be interesting to me whether you can force a locking of the ledger from an API perspective.

**Comment by jhartzell42** [comment]
Please build from `develop` for this feature for now.

**Comment by jhartzell42** [comment]
It's in there :-)

**Comment by jhartzell42** [comment]
Released! Thank you!
