### ISSUE TITLE
Compile problem

### ISSUE THREAD

**Issue by atlaschiew** [obsidiansystems/ledger-app-tezos#143]
hi, i was following exactly the compilation way you mentioned in readme. Unfortunately, i still facing error as show in picture below.
![Capture](https://user-images.githubusercontent.com/45816141/82788043-4485e800-9e9a-11ea-9fe8-04b9ca17a92d.PNG)

**below is my OS details:**
Distributor ID: Ubuntu
Description:    Ubuntu 20.04 LTS
Release:        20.04
Codename:       focal

please kindly advise. thanks

**Comment by ghost** [comment]
You seem to have closed the issue without telling the solution, did you find any? If so, what was the solution?
