### ISSUE TITLE
show ledger path not working properly

### ISSUE THREAD

**Issue by murbard** [obsidiansystems/ledger-app-tezos#26]
Running `tezos-client show ledger path ...` shows the following error. 

`APDU level error: Unexpected sequence number (expected 0, got 191)` on the console (3 times)
and `Unrecognized operation` on the ledger.

**Comment by jdsika** [comment]
I can confirm and already reported it on Reddit. But I need time to reproduce the error and deliver more details.

**Comment by jhartzell42** [comment]
Could you please post the entire error, not just those portions of it?

**Comment by jhartzell42** [comment]
Can you also please run it with `export TEZOS_LOG="client.signer.ledger -> debug"` first?

**Comment by jhartzell42** [comment]
This has to do with U2F support. On macOS, U2F support sometimes causes things not to go through at all -- retrying until it works is the current work-around. On Linux, this warning is spurious and has been changed to reflect that.

**Comment by jhartzell42** [comment]
We are working on completely getting rid of this glitch.

**Comment by 3noch** [comment]
This is a duplicate of #30. Please refer there for more details and how to resolve.
