### ISSUE TITLE
When will OSX support come?

### ISSUE THREAD

**Issue by skaht** [obsidiansystems/ledger-app-tezos#5]

**Comment by adrianbrink** [comment]
@jhartzell42 Do you know what those modifications are? I can't yet get the app to compile on macOS

**Comment by 3noch** [comment]
We should leave this open until we have a tested solution.

**Comment by matthewbauer** [comment]
Currently, development on Ledger is unavailable for macOS. You can still install the app on macOS through Ledger Live, but you must build it on Linux.

> Only Linux is supported as a development OS. For Windows and MacOS users, a Linux VM is recommended.

https://ledger.readthedocs.io/en/latest/userspace/getting_started.html
