### ISSUE TITLE
Readme: udev rules

### ISSUE THREAD

**Issue by jdsika** [obsidiansystems/ledger-app-tezos#88]
Was there a change of the udev rules script? I cannot see the entry to replace the plugdev group as described in the readme:

> At this point, please use your favorite editor to modify add_udev_rules.sh to your configuration, e.g., by replacing plugdev with an appropriate group for your system configuration. We recommend against running the next command without reviewing the script and modifying it to match your configuration.

I executed the script added my user to plugdev but I cannot see the connected ledger.

**Comment by matthewbauer** [comment]
Yeah, the udev rules have been changed recently for Ledger. You no longer need to have the plugdev group and can just rely on uaccess, provided you have a modern Systemd-based Linux distro. You can try out the older version here:

https://raw.githubusercontent.com/LedgerHQ/udev-rules/709581c85db97bf6ea12e472aa4e350bf0eabfb7/add_udev_rules.sh

If you still have an issue, it is best to report it on Ledger's repo:

https://github.com/LedgerHQ/udev-rules/issues

**Comment by jdsika** [comment]
@matthewbauer fyi the old rules using plugdev as a user group are working but the new one not.
