### ISSUE TITLE
Post Babylon: When trying to confirm transfer of XTZ from my kt1 to tz1 account, Ledger displays "Unrecognized Operation / Sign Hash" message

### ISSUE THREAD

**Issue by warrene33** [obsidiansystems/ledger-app-tezos#90]
I got the same error when using TezBox and Galleon, so the issue seems to be with the Ledger Tezos app. I am using v2.2.0

Comments from support from one of the wallet providers:
"Hi there, we can confirm that this is the only way to use [Wallet] with ledger currently until Obsidian updates the Ledger app. You will need to accept the unrecognized transaction if you want to continue with the tx – this isn’t recommended as it leaves you at risk of a MITM attack so it’s up to you if you decide to use it this way.

This is not an issue with [Wallet], as the transaction we are generating is valid – the developers of the Tezos ledger app need to make the correct changes so this displays correctly."

**Comment by mikereinhart** [comment]
v2.2.0 is expected to show "Sign Hash" when interacting with manager.tz. Our next release will include special parsing for the 4 manager.tz operations:
- Set Delegate
- Withdraw Delegate
- Transfer: Originated -> Originated
- Transfer: Originated -> Implicit

We'll close this issue when that release is available!

**Comment by fmarcoz** [comment]
Hi, I tried the version 2.2.1 but I still get 'Unrecognized Operation'

**Comment by mikereinhart** [comment]
Hi @fmarcoz - are you using a wallet provider or are you doing the operation over the command line? The outcome you are describing might be a result from somewhere else in the software stack, but we're happy to debug. Let us know!

**Comment by fmarcoz** [comment]
Hi @mikereinhart, I am using the command line.
I tried:
- tz1 to kt1 -> it works;
- tz1 to tz1 -> it works;
- kt1 to tz1 -> it doesn't work.

**Comment by jmininger** [comment]
Hello @fmarcoz :
To transfer from a KT1 contract running the manager.tz script, you must use the following command to invoke the contract. Direct transfers from KT1 accounts to tz1 accounts are not allowed (to my knowledge) by the Babylon protocol,  but you can run a transfer from the managing account to the kt1 account, (with the proper parameters passed in below) which has the effect of transferring from your kt1 account to another implicit account.
```
$TCLIENT transfer 0 from <implicit_manager_address>  to <KT1 contract address>  --entrypoint do --arg '{ DROP ; NIL operation ; PUSH key_hash "<tz1 address receiving the transfer>" ; IMPLICIT_ACCOUNT; PUSH mutez <transfer amount in mutez> ; UNIT ; TRANSFER_TOKENS ; CONS }' --dry-run
```

**Comment by fmarcoz** [comment]
Hi @jmininger,
your command works just fine with version 2.2.1 of the ledger wallet.
Where did you get that command from?
Thanks.

**Comment by mikereinhart** [comment]
Hi @fmarcoz - you can find the manager.tz operations here in the docs -https://tezos.gitlab.io/protocols/005_babylon.html#migration-from-scriptless-kt1s-to-manager-tz

We'll close this issue now that it seems all is settled!
